let engwords = [
    "Abandoned orphanage",
    "Ache",
    "Ambiguity",
    "Arch-nemesis",
    "Argue",
    "Arrogant",
    "Aversion",
    "Beloved",
    "Bent over",
    "Blank page",
    "Block",
    "Blood transfusion",
    "Bone marrow",
    "Breathe hard",
    "Bridge of the nose",
    "Bullshit",
    "Button",
    "Catharsis",
    "Chase",
    "Claim",
    "Clip",
    "Collect",
    "Corner",
    "Cornerstone",
    "Coupons",
    "Cover with",
    "Dead engine",
    "Delusion",
    "Distraction",
    "Disturbing",
    "Diversion",
    "Dope up",
    "Drawer",
    "Drum",
    "Dusty",
    "Emerge",
    "Envelope",
    "Essay",
    "Fiend",
    "Flip",
    "Fold",
    "Fonder",
    "Forensic unit",
    "Frayed",
    "Glad",
    "Glowing",
    "Goosebumps",
    "Grab",
    "Grasp",
    "Hallway",
    "Heir",
    "High Comedy",
    "Idiotic",
    "In-demand",
    "Infect",
    "Judgment",
    "Kidney",
    "Kneeling",
    "Medication",
    "Metabolism-wrecking",
    "Neurosurgeon",
    "Notoriety",
    "Offered up",
    "Otherwise",
    "Overwhelm",
    "Paranoid",
    "Paranoid delusions",
    "Peculiar",
    "Penley requirements",
    "Pinch",
    "Plan B",
    "Presumably",
    "Prisoner",
    "Provide backup",
    "Psychobabble",
    "Quitter",
    "Quote",
    "Reach",
    "Ruled paper",
    "Seem",
    "Seemingly",
    "Shivering",
    "Sigh",
    "Skyrocket",
    "Sleight of hand",
    "Spare",
    "Speck of bone marrow",
    "Spit",
    "Sprint",
    "Summon",
    "Sweat",
    "Tabloids",
    "Tear",
    "Ten-gallon",
    "Throbbing",
    "Throw",
    "Toss",
    "Towel",
    "Trash bag",
    "path",
    "hallway",
    "clutches",
    "shelf",
    "envelope",
    "stamped",
    "time being",
    "respective",
    "clutch",
    "scribbled",
    "frayed",
    "cornerstone",
    "ruled paper",
    "requirements",
    "spare",
    "heir",
    "Spare",
    "mother country",
    "What hell, being an adult!",
    "arch-nemesis",
    "kneeling",
    "betrayed",
    "sleight of hand",
    "paranoid delusions",
    "rout out",
    "meaningless",
    "psychobabble",
    "dope up",
    "collect the bill",
    "poker faced",
    "drumming",
    "Bridge of the nose",
    "Toss",
    "Throbbing",
    "Ambiguity",
    "Distraction"
]

engwords = [
    "антигитлеровская коалиция",
    "антифашистское подполье",
    "генеральный план «Ост»",
    "план «Барбаросса»",
    "блицкриг",
    "ГКО (Государственный Комитет Обороны)",
    "блокада",
    "Тегеранская конференция",
    "Ялтинская (Крымская) конференция ",
    "Потсдамская (Берлинская) конференция",
    "Брестская крепость",
    "оккупация",
    "партизанские отряды",
    "освободительная миссия Красной Армии ",
    "Коренной перелом в войне ",
    "приказ Nº 227 («Ни шагу назад!»)",
    "«рельсовая война»",
    "депортация",
"эвакуация",
"коллаборационизм",
"«власовцы»",
"«бандеровцы»",
"«лесные братья»",
"конццлагеря",
"Холокост",
"ленд-лиз",
"еак",
"народное ополчение",
"Совинформбюро",
"репатриация",
"второй фронт",
"капитуляция",
"Организация Объединенных Наций (ООН)",
"репарации",
"«Кукрыниксы»",
]



engwords=[
    "А.И. Антонов",
"И.Х. Баграмян",
"Б.Л. Ванников",
"А.М. Василевский",
"Н.Ф. Ватутин",
"Н.А. Вознесенский",
"К.Е. Ворошилов",
"Л.А. Говоров",
"А.А. Громыко",
"Л.М. Доватор",
"М.А. Егоров",
"А.А. Жданов",
"Г.К. Жуков",
"Р. Зорге",
"М. Казей",
"М.В. Кантария",
"Д.М. Карбышев",
"В.Г. Клочков",
"С.А. Ковпак",
"И.Н. Кожедуб",
"И.С. Конев",
"З.А. Космодемьянская",
"В. Котик",
"О.В. Кошевой",
"Н.И. Кузнецов",
"Н.Г. Кузнецов",
"М.М. Литвинов",
"И.М. Майский",
"Р.Я. Малиновский",
"В.А. Малышев",
"К.А. Мерецков",
"В.М. Молотов",
"Х.Н. Нурадилов",
"Д.Г. Павлов",
"И.В. Панфилов",
"М.Г. Первухин",
"А.И. Покрышкин",
"П.К. Пономаренко",
"К.К. Рокоссовский",
"И.В. Сталин",
"В.В. Талалихин",
"С.К. Тимошенко",
"Ф.И. Толбухин",
"Д.Ф. Устинов",
"А.Ф. Федоров",
"И.Д. Черняховский",
"В.И. Чуйков",
"Б.М. Шапошников",
"А.И. Шахурин",
"Н.М. Шверник",
"М.С. Шумилов",
"О.Ф. Берггольц",
"В.С. Гроссман",
"М. Джалиль",
"Ю.Б. Левитан",
"Л.А. Русланова",
"патриарх Сергий",
"К.С. Симонов",
"А.Т. Твардовский",
"Д.Д. Шостакович",
"Антонов О. К.",
"В.А. Дегтярев",
"С.В. Ильюшин",
"М.И. Кошкин",
"С.А. Лавочкин",
"Е.О. Патон",
"А.Н. Туполев",
"Г.С. Шпагин",
"А.С. Яковлев",
"Н.Н. Поликарпов",
"Ф.В. Токарев",
]
export {engwords}