let engwords = [
    "Abandoned orphanage",
    "Ache",
    "Ambiguity",
    "Arch-nemesis",
    "Argue",
    "Arrogant",
    "Aversion",
    "Beloved",
    "Bent over",
    "Blank page",
    "Block",
    "Blood transfusion",
    "Bone marrow",
    "Breathe hard",
    "Bridge of the nose",
    "Bullshit",
    "Button",
    "Catharsis",
    "Chase",
    "Claim",
    "Clip",
    "Collect",
    "Corner",
    "Cornerstone",
    "Coupons",
    "Cover with",
    "Dead engine",
    "Delusion",
    "Distraction",
    "Disturbing",
    "Diversion",
    "Dope up",
    "Drawer",
    "Drum",
    "Dusty",
    "Emerge",
    "Envelope",
    "Essay",
    "Fiend",
    "Flip",
    "Fold",
    "Fonder",
    "Forensic unit",
    "Frayed",
    "Glad",
    "Glowing",
    "Goosebumps",
    "Grab",
    "Grasp",
    "Hallway",
    "Heir",
    "High Comedy",
    "Idiotic",
    "In-demand",
    "Infect",
    "Judgment",
    "Kidney",
    "Kneeling",
    "Medication",
    "Metabolism-wrecking",
    "Neurosurgeon",
    "Notoriety",
    "Offered up",
    "Otherwise",
    "Overwhelm",
    "Paranoid",
    "Paranoid delusions",
    "Peculiar",
    "Penley requirements",
    "Pinch",
    "Plan B",
    "Presumably",
    "Prisoner",
    "Provide backup",
    "Psychobabble",
    "Quitter",
    "Quote",
    "Reach",
    "Ruled paper",
    "Seem",
    "Seemingly",
    "Shivering",
    "Sigh",
    "Skyrocket",
    "Sleight of hand",
    "Spare",
    "Speck of bone marrow",
    "Spit",
    "Sprint",
    "Summon",
    "Sweat",
    "Tabloids",
    "Tear",
    "Ten-gallon",
    "Throbbing",
    "Throw",
    "Toss",
    "Towel",
    "Trash bag",
    "path",
    "hallway",
    "clutches",
    "shelf",
    "envelope",
    "stamped",
    "time being",
    "respective",
    "clutch",
    "scribbled",
    "frayed",
    "cornerstone",
    "ruled paper",
    "requirements",
    "spare",
    "heir",
    "Spare",
    "mother country",
    "What hell, being an adult!",
    "arch-nemesis",
    "kneeling",
    "betrayed",
    "sleight of hand",
    "paranoid delusions",
    "rout out",
    "meaningless",
    "psychobabble",
    "dope up",
    "collect the bill",
    "poker faced",
    "drumming",
    "Bridge of the nose",
    "Toss",
    "Throbbing",
    "Ambiguity",
    "Distraction"
]
export {engwords}